//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_arc_actionset_trigger;
        
        private static SteamVR_Action_Boolean p_arc_actionset_grip;
        
        private static SteamVR_Action_Boolean p_arc_actionset_menu;
        
        public static SteamVR_Action_Boolean arc_actionset_trigger
        {
            get
            {
                return SteamVR_Actions.p_arc_actionset_trigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean arc_actionset_grip
        {
            get
            {
                return SteamVR_Actions.p_arc_actionset_grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean arc_actionset_menu
        {
            get
            {
                return SteamVR_Actions.p_arc_actionset_menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.arc_actionset_trigger,
                    SteamVR_Actions.arc_actionset_grip,
                    SteamVR_Actions.arc_actionset_menu};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.arc_actionset_trigger,
                    SteamVR_Actions.arc_actionset_grip,
                    SteamVR_Actions.arc_actionset_menu};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.arc_actionset_trigger,
                    SteamVR_Actions.arc_actionset_grip,
                    SteamVR_Actions.arc_actionset_menu};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.arc_actionset_trigger,
                    SteamVR_Actions.arc_actionset_grip,
                    SteamVR_Actions.arc_actionset_menu};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_arc_actionset_trigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arc_actionset/in/trigger")));
            SteamVR_Actions.p_arc_actionset_grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arc_actionset/in/grip")));
            SteamVR_Actions.p_arc_actionset_menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arc_actionset/in/menu")));
        }
    }
}
