//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_arc_actionset p_arc_actionset;
        
        public static SteamVR_Input_ActionSet_arc_actionset arc_actionset
        {
            get
            {
                return SteamVR_Actions.p_arc_actionset.GetCopy<SteamVR_Input_ActionSet_arc_actionset>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_arc_actionset = ((SteamVR_Input_ActionSet_arc_actionset)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_arc_actionset>("/actions/arc_actionset")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.arc_actionset};
        }
    }
}
