//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_arc_actionset : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean trigger
        {
            get
            {
                return SteamVR_Actions.arc_actionset_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip
        {
            get
            {
                return SteamVR_Actions.arc_actionset_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.arc_actionset_menu;
            }
        }
    }
}
